### ISSUE TITLE
Loop stop condition bug? : player_with_effect_mic.ino

### ISSUE THREAD

**Issue by sowd** [TomonobuHayakawa/Spresense-Playground#23]
Hi,

I am not very sure, but I wonder if:

L. 50 of
./sketches/AudioPlayers/player_with_effect_mic/player_with_effect_mic.ino

`for (uint32_t cnt = 0; cnt < size; cnt += channel_number){`

should be

`for (uint32_t cnt = 0; cnt < size/2; cnt += channel_number){`

Could you check?

Shigeru

**Comment by TomonobuHayakawa** [comment]
Dear @sowd 

I'm very very sorry.
Your point is correct.
Fixed.

Thank you very much for pointing out.

**Comment by sowd** [comment]
Please do not feel sorry.
It is a super useful sample that i have been really wanted!!

Shigeru
